### ISSUE TITLE
Some problems using the $ end anchor

### ISSUE THREAD

**Issue by vmagnin** [perazz/fortran-regex#3]
Considering the `character(*), parameter :: text = 'table football'` string in the `test\tests.f90` file, the regex `ll$` works,
but `l$` returns the two final `ll`
and `l.$` crashes:
```bash
At line 88 of file test/tests.f90
Fortran runtime error: Substring out of bounds: upper bound (16) exceeds string length (14)

Error termination. Backtrace:
#0  0x7f9475023ad0 in ???
#1  0x7f9475024649 in ???
#2  0x7f9475024c46 in ???
#3  0x55fe89e9142a in test_bracket_space
        at test/tests.f90:88
#4  0x55fe89e91765 in tests
        at test/tests.f90:25
#5  0x55fe89e91edd in main
        at test/tests.f90:2
<ERROR> Execution failed for object " regex_tests "
<ERROR>*cmd_run*:stopping due to failed executions
STOP 1
```

**Comment by perazz** [comment]
This problem seems to affect the parent library too: I've filed that [here](https://github.com/kokke/tiny-regex-c/issues/84#issue-1501805702), now investigating.

**Comment by perazz** [comment]
OK apparently fixed by the latest commit. Pattern match length was not reset every time the search advanced. I'll propagate this to a pull request in tiny-regex-c too
