### ISSUE TITLE
Fortran runtime error: Substring out of bounds: upper bound (3) of 'str' exceeds string length (2)

### ISSUE THREAD

**Issue by skphy** [perazz/fortran-regex#6]
@perazz ;  here I am adding the program with the mentioned error:
`program main
   use regex_module

   implicit none
   integer :: idx,ln
   character(*), parameter :: text = 'Avida Dollar$'

   idx = REGEX(string=text, pattern='[A-Z][a-z]+\$', length=ln)

   print '(I0, "|", A ,"|")', idx, text(idx:idx+ln-1)
end program main`

- fpm.toml contains the following dependencies:
   [dependencies]
   fortran-regex = { git = "https://github.com/perazz/fortran-regex", branch = "main" }

- fpm run
 Project is up to date
At line 248 of file build/dependencies/fortran-regex/src/regex.f90
Fortran runtime error: Substring out of bounds: upper bound (3) of 'str' exceeds string length (2)

**Comment by perazz** [comment]
I've added your testcase in commit da01ce4a6020f40f5fdd12e2a8b6868fa5e1d079 and everything runs fine. 
I believe the issue may have been solved by the previous commits. Please update the repo. Closing from now.

**Comment by skphy** [comment]
works now!
